-- MySQL Script generated by MySQL Workbench
-- qui 09 jan 2020 00:29:45 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vexta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vexta
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `vexta` DEFAULT CHARACTER
SET utf8 ;
USE `vexta`
;

-- -----------------------------------------------------
-- Table `vexta`.`clientes`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `vexta`.`clientes`
(
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR
(100) NOT NULL,
  `city` VARCHAR
(100) NOT NULL,
  `state` VARCHAR
(100) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY
(`id`))
ENGINE = InnoDB
DEFAULT CHARACTER
SET = utf8;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;


--- ADDING NEW COLUMN COUNTY
alter table clientes
add column county varchar
(150);
